### ISSUE TITLE
Stake Girls obstructing the screen

### ISSUE THREAD

**Issue by Yugikun** [07th-mod/umineko-question#53] opened 2017-01-12 07:00 UTC
Hi. Me again. I was playing through episode 4 and after a certain point when I quit the game and reloaded it all the sprites for the stake girls except for Mammon decided to put themselves on the screen. Screenshot here (https://gyazo.com/49d5fea4bc89a3be2e852b839d75dca2). In addition to obstructing the background, they also put themselves over any sprite that happens to be on the right of the screen, which is a bit of an issue. Any way to fix this?

**Comment by drojf** [comment] 2017-01-12 07:23
If you're comfortable editing the script (the `0.utf` file), you can find the part just after you saved and add the "clear all sprites" command. You can find your position in the script by searching the text file for the dialogue that appears when you load the save.

`csp -1`

which should clear all the sprites on the screen. Of course you could also load your best working save and then skip forward to the same point...unless I'm misunderstanding and this always happens every time you reach that point in the game?

Also, could you upload the offending save file so we have it as reference? I don't think I'll investigate it but it's good to keep a record.

**Comment by Yugikun** [comment] 2017-01-12 07:58
https://www.mediafire.com/?dhdxfzhz1fz7l16 The issue's fixed! I also got an upload of my save, I think. Sorry for the mediafire link.

**Comment by Yugikun** [comment] 2017-01-12 08:00
Actually, turns out there's a bit more to it. If I choose to switch to the old sprites or opt to save/load my game, the sprites come back for some reason. The game is still playable, though, and I now know how to remove them.

**Comment by drojf** [comment] 2017-01-12 08:49
oh actually looks like the stake girls loading code has been modified by us (@ReitoKanzaki ). I better let him handle it

For reference, I tried doing

```
csp_var 113
csp_var 112
csp_var 111
csp_var 4
csp_var 3
csp_var 2
csp_var 1
```
Then saving/load or pressing the switch to original images button, but one of the stake girls still appears (the far right one)

I was looking at this section:

```
;lsp 899,$RG7_hohoemiA1,-160,50
lsp_var 113,$RG7_hohoemiA1,-159,50  ;convert to widescreen
se2 52
print 99,300,"breakup.dll/lrp"

;lsp 898,$RG6_akuwaraiA1,-64,50
lsp_var 112,$RG6_akuwaraiA1,-37,50  ;convert to widescreen
se1 52
print 99,300,"breakup.dll/lrp"

;lsp 897,$RG5_akuwaraiA2,32,50
lsp_var 111,$RG5_akuwaraiA2,85,50  ;convert to widescreen
se3 52
print 99,300,"breakup.dll/lrp"

;lsp 896,$RG4_defA1,128,50
lsp_var 4,$RG4_defA1,207,50  ;convert to widescreen
se2 52
print 99,300,"breakup.dll/lrp"

;lsp 895,$RG3_fumanA1,224,50
lsp_var 3,$RG3_fumanA1,329,50  ;convert to widescreen
se1 52
print 99,300,"breakup.dll/lrp"

;lsp 894,$RG2_hohoemiA1,320,50
lsp_var 2,$RG2_hohoemiA1,451,50  ;convert to widescreen
se3 52
print 99,300,"breakup.dll/lrp"

;lsp 893,$RG1_hohoemiA1,80,0
lsp_var 1,$RG1_hohoemiA1,146,0  ;convert to widescreen
se3 52
print 99,300,"breakup.dll/lrp"

bgm1 7

langjp　１人、２人、３人。@４人、５人、６人、７人…。@
langen^1, 2, 3 people.^@^  4, 5, 6, 7 people...^@
```

**Comment by drojf** [comment] 2017-01-12 08:57
You could try putting a label just after the broken save. Then put a 'goto' statement after your latest working save. When you load your latest working save, you should jump forward immediately instead of having the skip forward ... but that leads me to wonder, how often do you save? or are you the type who only keeps one save file?

make a label:
```
<broken save point here>
*after_broken_save_label
````

goto the label:
```
<last working save point here>
goto *after_broken_save_label
```

If your last save is in ep 1 I can't be sure that it will work, but if you have a save in ep 4 it might work OK.

Note that modifying the script will make all saves after that point in the script move backwards slightly in the script (possibly messing up things).

**Comment by Yugikun** [comment] 2017-01-13 08:26
I save sorta often. Mostly whenever I stop playing the game (and if a session of playing is particularly long, sometimes in between me starting and stopping as well) or if I want to test out something, in which those saves go into the non save-1 slot.

Also, I'm not quite sure what I'm supposed to do. Do I put the label in the script doc? Do I put the label in as you stated it or do I put something else in (and if so, what should I?)

**Comment by drojf** [comment] 2017-01-13 08:45
hmm...if you save sorta often, couldn't you just load your most recent working save, then hold CTRL to skip until you get to where you were before? or am I missing something here?

You can make the label name anything, as long as it matches in both cases. All I was saying is that you can jump anywhere in the script by using the `goto` statement. However if you save often it's just easier to hold down CTRL and skip forward through the game...

```
goto *[LABEL NAME GOES HERE]
....
[lots of lines of script here]
.....
*[LABEL NAME GOES HERE]
```

**Comment by Yugikun** [comment] 2017-01-13 09:47
That's possible, although an issue there is that none of the saves I have of episode 4 are at a point before the stake girls glitch started appearing, which means that I have to skip my way through a sizable chunk of the episode.

...Actually, do you happen to have a save file at a point before the first appearance of gaap within episode 4? If you don't or if it's hard to attain one I won't mind, but it'd probably be a better alternative to skipping through the entire episode again thus far.

**Comment by Yugikun** [comment] 2017-01-14 04:09
Took a look around on that save and yeah, that seems to fix things.

Thanks!

**Comment by Yugikun** [comment] 2017-01-14 04:17
Checked it out, and I think the problems solved now. The stake girls aren't appearing, and although saving and loading it at one point just took me to the title screen, doing it further points from that seems to make things work again.

Thanks!

**Comment by drojf** [comment] 2017-01-14 04:22
Cool, I'll leave this issue as open so that @ReitoKanzaki can have a look at it later

**Comment by Maelstrom1** [comment] 2017-01-24 22:10
Weird problem, but somewhat similar. The same thing happened to me, but as early as the first Chiester sister murder. I fixed this by loading an earlier save, skipping, and saving slightly earlier. Weirdly enough, despite not saving and loading, the 7 stake sisters appeared and refused to go away directly after the mini-cutscene thing where Gaap appeared. Loading the "fixed" save I had created made the sisters appear again..... Any help/tips?

**Comment by Blulaz** [comment] 2017-01-26 11:49
Can confirm problem appearing to me on EP4. Not sure about the rest of the EP as i skipped them since i played those ch in the old WitchHunt translation. The problem seems to be appearing during the 1998 part when Ange having a conversation with Mammon on the boat, after calling Sakutaro. If you save exactly after the scene where it shows all of the 6 Stakes (Except Mammon), the bug occured.

**Comment by pmrowla** [comment] 2017-03-20 08:02
I have the same issue in ep4. If I create a save at any point after the boat scene mentioned by @Blulaz, the next time I load that save the 7 sisters sprites will be on the screen. Editing the script to clear all sprites solves the problem temporarily, but if I advance the game and make a new save later in the game the 7 sisters sprites will reappear. I can just work around this by editing the script every time I save my progress, but obviously that's not ideal.

I also tested restarting the entire chapter and skipping ahead to where I was previously, and then creating a new save - same issue.

**Comment by drojf** [comment] 2017-03-20 09:23
hey guys. I was planning having @ReitoKanzaki  fix it, but I guess he's disappeared so I'll try take a look at it.

Can you quite a sentence from when that section starts so I can find it in the script?  

The first section I know about has the text `Then, a pale light began to gather in her palms, ......and one by one, the girls began to show themselves` just before it. Is it that section? or earlier?

**Comment by pmrowla** [comment] 2017-03-20 09:44
The bug starts in the section with the text ```At some point, ...the rest of the Seven Sisters had gathered on the deck.``` Right before that line, the 6 sprites are displayed and any of my saves after that point will have the bug where those 6 sprites also appear.

The bug does not occur for me after the section you mentioned (which is before the boat scene), so it looks like any differences in how the 6 sprites are displayed in those two scenes would be a good place might be what's causing the problem.

**Comment by drojf** [comment] 2017-03-20 09:55
It looks like it's just missing the 

```
csp_var 113
csp_var 112
csp_var 111
csp_var 4
csp_var 3
csp_var 2
csp -1
```

(I assume saved variables which remembers which sprites are active)

I tried it just now and it works for me. Please try and reproduce it on your side:

1. Find the line `The Seven Sisters of Purgatory, right here`, after which they are meant to disappear
2. Just after that should be the line `csp -1`
3. Add 

```
csp_var 113
csp_var 112
csp_var 111
csp_var 4
csp_var 3
csp_var 2
```

Just before the `csp -1` . This should clear the variables which remembers that the sprites should remain on-screen.

It's strange - I thought the problem was harder than this but whatever works :D

**Comment by pmrowla** [comment] 2017-03-20 10:04
Those lines are already in my script at that point (that's the scene that works properly and doesn't cause the save bug afterwords). But yeah, that does fix the save issue after the bugged scene, thanks!

My changes:
```diff
langen:dwave 0, enj_4e1240:^"You certainly do exist.^@:dwave 0, enj_4e1241:^  Lucifer.^@:dwave 0, enj_4e1242:^  And Leviathan.^@:dwave 0, enj_4e1243:^  And Satan.^@:dwave 0, enj_4e1244:^  And Belphegor.^@:dwave 0, enj_4e1245:^  And Mammon.^@:dwave 0, enj_4e1246:^  And Beelzebub.^@:dwave 0, enj_4e1247:^  And Asmodeus.^@:dwave 0, enj_4e1248:^  ...And Sakutarou too."^\

csp -1
+csp_var 113
+csp_var 112
+csp_var 111
+csp_var 4
+csp_var 3
+csp_var 2
+
bg Ship_S2af,0  ;fixed lighting issue
ld r,$RG1_komaruA2,23

**Comment by ArmandBernard** [comment] 2017-03-28 02:17
@pmrowla's changes fixed it for me as well.

**Comment by drojf** [comment] 2017-03-28 02:26
Did you download the latest release? I updated it so it should have already been fixed if you downloaded it in the last 8 days (the 0.utf file only). Just wondering because if you did download it recently and it didn't fix it, I screwed something up... If you downloaded it more than 8 days ago everything is fine.

**Comment by ArmandBernard** [comment] 2017-03-28 02:31
I downloaded it a few weeks back I believe. Probably right before you made the patch.

**Comment by drojf** [comment] 2018-02-23 09:39
This should be fixed now.

**Closed by drojf** 2018-02-23 09:39 UTC
