### ISSUE TITLE
Install Issues on Mac

### ISSUE THREAD

**Issue by distoclex** [07th-mod/umineko-question#19] opened 2016-09-29 19:25 UTC
Hey guys,

The voice patch seems to work fine, but the graphics will refuse to work on Steam. I followed all of the instructions on GitHub, however, only the voice will come through. The "0.utf" file shows a blank page rather than a black box with a blue outline, which is typical for the original file. I don't know how to resolve this.

**Comment by ItaloKnox** [comment] 2016-09-29 19:27
Can you make sure your folder structure is just like this?
![](https://1.lithi.io/xmhg.png)

**Comment by distoclex** [comment] 2016-09-29 19:33
![screen shot 2016-09-29 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/22529803/18969185/a64211c8-8651-11e6-915a-f199de9481f6.png)

Here is what I have...should I arrange it to look exactly like this? Where is the .DS_Store?

**Comment by ItaloKnox** [comment] 2016-09-29 19:37
You are missing the ``bmp`` folder, I think that's the issue here. What's inside the ``umineko_graphics`` folder? You are supposed to extract the content of ``umineko_graphics.zip`` inside the root folder. If there's anything inside the ``umineko_graphics`` folder, try moving it to the root.

**Comment by ReitoKanzaki** [comment] 2016-09-29 19:40
I don't have a Mac, but because the patch edits the executable to force a specific resolution, the widescreen patch and other graphics will not look the same unless the Mac executable is edited as well. Unless I'm mistaken.

**Comment by distoclex** [comment] 2016-09-29 19:42
The overlay in the main screen has changed, the opening screen has changed. However, the sprites are still only original and Steam. My save files are no longer corrupted. It is strange. So I transferred the files inside the the "umineko_graphics" folder to the main Umineko folder, but I left the "big" file inside of the graphics folder because the "umineko fix" patch seemed to have replaced the "big" folder? What do I do now? We're getting so close!

**Comment by ItaloKnox** [comment] 2016-09-29 19:44
@ReitoKanzaki
That makes sense, I forgot that Mac doesn't use .exes. In fact this should only affect his resolution, so the graphics should load normally.

@distoclex 
Without the ``big`` folder you won't get the new sprites. Put it inside the root and replace any files when asked.

**Comment by distoclex** [comment] 2016-09-29 19:48
Success!!! Graphics patch success!! Thank you, thank you, thank you, thank you, thank you, thank you, thank you! This is awesome!!

**Comment by ItaloKnox** [comment] 2016-09-29 19:48
Congrats! 👍 

Can you screenshot the game running? Just so we can check the resolution. If it's not correct, we will try to fix this asap for you. :)

**Comment by distoclex** [comment] 2016-09-29 20:03
Sure thing! But, um...my voice patch seems to not be working, haha.

**Comment by distoclex** [comment] 2016-09-29 20:04
![screen shot 2016-09-29 at 3 03 20 pm](https://cloud.githubusercontent.com/assets/22529803/18970196/f0e31570-8655-11e6-923a-0ad8cdb7f6e6.png)

Here is the full screen screenshot!!!

**Comment by ItaloKnox** [comment] 2016-09-29 20:06
Reinstall the ``0.utf`` and try starting a new save to see if the voices will come back.

Also, did you take this screenshot in fullscreen? I guess the aspect ratio is not what we wanted it to be. (paging @drojf to solve this)

By the way, the backgrounds are not loading correctly. I guess the ``0.utf`` file is broken or you don't have the PS3 backgrounds in ``\bmp\background``. Try checking this for me.

**Comment by distoclex** [comment] 2016-09-29 23:53
![screen shot 2016-09-29 at 6 51 59 pm](https://cloud.githubusercontent.com/assets/22529803/18976240/019667d0-8676-11e6-8004-4c13cd527db0.png)

My resolution got weird. After fixing this issue, it should be fine!

**Comment by drojf** [comment] 2016-09-30 00:53
I feel pretty dumb, i didn't even know the game was released on mac until now!

Could you somehow send me the original mac executable? I might be able to patch it the same way I patched the windows version.

If you're using the original executable, the text won't appear correctly on the screen because we modified the script so that the text appears across the whole screen, the game won't be in widescreen mode, and the backgrounds will be slightly zoomed in (as it appears in your screenshot).

**Comment by distoclex** [comment] 2016-09-30 00:59
[Umineko1to4.exe.zip](https://github.com/07th-mod/umineko-question/files/501974/Umineko1to4.exe.zip)

Here is the original file. Thank you very much @drojf !!!

**Comment by drojf** [comment] 2016-09-30 08:17
er i meant the umineko1to4.app file, not the exe file sorry

**Comment by drojf** [comment] 2016-09-30 08:23
sorry to comment again, but please send whichever file you launch to start the game. sorry, I'm noob at Mac OS X so I don't know exactly which file it is that you launch. 

I'm pretty sure its' the .app file, but according to some stuff I just read i first need to extract the .app file to get to the raw mac executable which I can then patch.

so yea, send me the file you click which launches the game :S

**Comment by distoclex** [comment] 2016-09-30 15:30
[Umineko1to4.app.zip](https://github.com/07th-mod/umineko-question/files/503283/Umineko1to4.app.zip)

I hope this is what you need.

**Comment by drojf** [comment] 2016-09-30 23:53
Hi @distoclex, try this [patchUminekoToWidescreenMAC.zip](https://github.com/07th-mod/umineko-question/files/503997/patchUminekoToWidescreenMAC.zip) . I patched the "umineko4" file in the "MacOS" directory.

Well, it _seems_ to have worked fine, I just used my old patch script but made the matching less strict. It replaced 1 instance of 1280 with with 1707 (the width) and one instance of 960 with 960 (the height, no change), so I think it's correct. 

modified script is here, however needs some work so that it's easier to use: https://gist.github.com/drojf/016a9e01810955ca285813020cf1a278

**Comment by distoclex** [comment] 2016-10-01 03:16
Hey man,

The app you sent me somehow...won't open. But then I put the original .app file there...then it works just fine. I have the same issue as before. What am I missing?

**Comment by distoclex** [comment] 2016-10-01 03:17
Thank you for all your hard work! I guess we still have to troubleshoot!

**Comment by drojf** [comment] 2016-10-01 04:12
So just to be sure, you should only have to replace the `umineko4` file in `Umineko\Umineko1to4.app\Contents\MacOS` with the corresponding one I gave you. All the other files should stay the same. What error message (if any) do you get when you try to launch the game? You should launch the game normally, you don't need to double click on the .app file or anything (I think).

Unfortunately I don't know enough about Mac OS X to fix much more than this, maybe if someone comes along who knows even a little they may be able to figure out why it won't launch ( either it's something simple or there's some internal checking to see if the mac executable has been changed).

----

I just realized that the windows version includes the mac binaries, so I didn't need to ask you for the file in the first place :S.

**Comment by distoclex** [comment] 2016-10-01 05:54
Thank you for your help. Maybe I'll restart my computer and try again. You've been awesome!

**Comment by Pyro165** [comment] 2016-10-18 09:01
Hi everyone! Many thanks for this great mod! It's just awesome.
I only have a little problem, I did almost everything and the voices and sprites work just fine.But I have the same problem with the text, I've tried to replace just the umineko4 file as you said but if I do that all the game won't work anymore. If I don't do that the game works fine, maybe I missed something? I've got a mac and I find strange that for distoclex worked and for me it doesn't

**Comment by drojf** [comment] 2016-10-18 11:08
I don't think @distoclex ever confirmed it working. I had more of a look at it just now, and I think I found the correct instruction to replace (hopefully). Attached is the new umineko4 file. Please let me know how it goes.

[umineko4.zip](https://github.com/07th-mod/umineko-question/files/536024/umineko4.zip)

I found the correct instruction by looking in the mac executable for '1280' and '960' as shorts (not ints as in the windows version) which were close together (as I knew they were close together from the windows version). There was only one match which was 4 bytes apart, which is the one I have (hopefully) replaced. The disassembly also checks out, from an online disassembly tool:

```
0:  66 b8 00 05             mov    ax,0x500
4:  66 b9 c0 03             mov    cx,0x3c0
```

**Comment by Pyro165** [comment] 2016-10-18 11:35
Yes! I tried quickly but now it works without any problem! Text, sound, sprites are perfect, Thanks!

**Comment by drojf** [comment] 2016-10-18 12:40
ah good good... I updated the V1.1 release to add the mac binary, so I'll mark this issue as closed now.

The script to patch the MacOS executable to widescreen can be found at: 

https://github.com/07th-mod/umineko-question/blob/master/widescreen/patchUminekoToWidescreenMacOS.py

**Comment by XxIvan2398Xx** [comment] 2017-09-29 20:11
Im having the same text issue I'm not sure how to fix it.  :( sorry I don't get get how patching quite works everything is shifted a bit just like in the picture please help ;(

**Comment by Pyro165** [comment] 2018-08-15 19:56
Hello, I'm here for a little problem with the Answer Arc.
Voices and sprites are perfect (thank you for the work!) but when there's some effects for them or the background it doesn't work on all the window. It looks similar to the problem for the Question Arc but just for the effects
<img width="1280" alt="schermata 2018-08-15 alle 21 43 44" src="https://user-images.githubusercontent.com/22908052/44169734-ad410d80-a0d5-11e8-9727-e390f3c36381.png">

**Comment by drojf** [comment] 2018-08-16 00:34
that's...a very interesting issue. just to confirm, you installed the patch recently (manually) using the instructions here: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac ?

Also, can you post some more screenshots? it looks like your script is OK, but perhaps some of the assets are missing...are you sure all the archives downloaded successfully? (when extracting them, did they give any errors?)

Also, your screen resolution is not 16:9, do you have a 16:10 ratio monitor (I don't think it makes any difference, but worth asking).

**Comment by Pyro165** [comment] 2018-08-16 10:04
Yes, I downloaded the manual patch yesterday and had no problem while extracting and I confirm that my screen resolution is 16:10.
I have to clarify, the game is perfectly playable like this, the issue is only for some effects of sprites & background. Some example in fullscreen:
This is the starting page
<img width="1280" alt="schermata 2018-08-16 alle 11 59 15" src="https://user-images.githubusercontent.com/22908052/44202395-25e2b100-a14c-11e8-9c34-ac724b9cdb20.png">
the Loading
<img width="1280" alt="schermata 2018-08-16 alle 11 59 22" src="https://user-images.githubusercontent.com/22908052/44202434-3eeb6200-a14c-11e8-90ba-42c29d78d71e.png">
When you load the save usually all the screen become white but here you can see that it act like there're 2 screen
<img width="1280" alt="schermata 2018-08-16 alle 11 59 23" src="https://user-images.githubusercontent.com/22908052/44202443-46127000-a14c-11e8-8739-a1dcdae0fcc3.png">
Or when you load from inside the game and the screen shatter
<img width="1280" alt="schermata 2018-08-16 alle 12 00 35" src="https://user-images.githubusercontent.com/22908052/44202520-81ad3a00-a14c-11e8-96aa-bd54aacc104d.png">

**Comment by drojf** [comment] 2018-08-16 23:44
To me, it looks like the graphics archive or the updates archive failed to extract or download correctly. Please check the folder `[Umineko Chiru game folder]\bmp\efe` for a image called `ware.png` - this is the 'screen shatter' image. If your screen shatter image is not 16:9, I'm probably correct about your issue. 

To fix the issue, I would recommend re-downloading the graphics patch and update zip for Chiru.
Make sure to download all three parts of the graphics patch, and the update zip: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac  . When extracting, be sure to check for any errors during the extraction.




There is also the issue of the save/load floating randomly at the bottom right of the screen...not sure what that's all about :S.

**Comment by drojf** [comment] 2018-08-16 23:46
Hold on a second, why is your first screenshot from the answer arcs, but the next few screenshots are from the question arcs?

**Comment by Pyro165** [comment] 2018-08-17 10:58
The first screenshot was from one of the first scene of the answer arc, were there's the prologue.
Anyway, just as you said probably something went wrong with the graphics patch and just by re-extracting everything is fixed, even the save/load thing, thank you so much!

**Comment by drojf** [comment] 2019-01-25 17:24
I'm closing this thread and opening a new one, more focussed on fixing the macos issues we know about: https://github.com/07th-mod/umineko-question/issues/123

**Closed by drojf** 2019-01-25 17:24 UTC
